name=PsaComfortCanAdapter
version=0.2.2
author=Ludwig V. <https://github.com/ludwig-v>, Nick V. (V3nn3tj3) <https://github.com/v3nn3tj3>
maintainer=Kolabse <kolabse@yandex.ru>
sentence=Arduino library to operate new PSA comfort devices (CAN2010) on old BSI CAN-BUS (CAN2004)
paragraph=run NAC, RCC, CIROCCO
category=Communication
url=https://github.com/ludwig-v/arduino-psa-comfort-can-adapter
includes=PsaComfortCanAdapter.h
depends=autowp-mcp2515
architectures=*
